#define str2qsv(a) 	     if(!stricmp(a,"QSV_BOOT_DRIVE"))			qsv=QSV_BOOT_DRIVE; \
	else if(!stricmp(a,"QSV_DYN_PRI_VARIATION"))	qsv=QSV_DYN_PRI_VARIATION; \
	else if(!stricmp(a,"QSV_FOREGROUND_FS_SESSION"))qsv=QSV_FOREGROUND_FS_SESSION; \
	else if(!stricmp(a,"QSV_FOREGROUND_PROCESS"))	qsv=QSV_FOREGROUND_PROCESS; \
	else if(!stricmp(a,"QSV_INT10ENABLED"))		qsv=QSV_INT10ENABLED; \
	else if(!stricmp(a,"QSV_MAX"))					qsv=QSV_MAX; \
	else if(!stricmp(a,"QSV_MAXHPRMEM"))			qsv=QSV_MAXHPRMEM; \
	else if(!stricmp(a,"QSV_MAXHSHMEM"))			qsv=QSV_MAXHSHMEM; \
	else if(!stricmp(a,"QSV_MAXPRMEM"))			qsv=QSV_MAXPRMEM; \
	else if(!stricmp(a,"QSV_MAXPROCESSES"))		qsv=QSV_MAXPROCESSES; \
	else if(!stricmp(a,"QSV_MAXSHMEM"))			qsv=QSV_MAXSHMEM; \
	else if(!stricmp(a,"QSV_MAX_COMP_LENGTH"))		qsv=QSV_MAX_COMP_LENGTH; \
	else if(!stricmp(a,"QSV_MAX_PATH_LENGTH"))		qsv=QSV_MAX_PATH_LENGTH; \
	else if(!stricmp(a,"QSV_MAX_PM_SESSIONS"))		qsv=QSV_MAX_PM_SESSIONS; \
	else if(!stricmp(a,"QSV_MAX_SLICE"))			qsv=QSV_MAX_SLICE; \
	else if(!stricmp(a,"QSV_MAX_TEXT_SESSIONS"))	qsv=QSV_MAX_TEXT_SESSIONS; \
	else if(!stricmp(a,"QSV_MAX_VDM_SESSIONS"))	qsv=QSV_MAX_VDM_SESSIONS; \
	else if(!stricmp(a,"QSV_MAX_WAIT"))			qsv=QSV_MAX_WAIT; \
	else if(!stricmp(a,"QSV_MIN_SLICE"))			qsv=QSV_MIN_SLICE; \
	else if(!stricmp(a,"QSV_MS_COUNT"))			qsv=QSV_MS_COUNT; \
	else if(!stricmp(a,"QSV_NUMPROCESSORS"))		qsv=QSV_NUMPROCESSORS; \
	else if(!stricmp(a,"QSV_PAGE_SIZE"))			qsv=QSV_PAGE_SIZE; \
	else if(!stricmp(a,"QSV_TIMER_INTERVAL"))		qsv=QSV_TIMER_INTERVAL; \
	else if(!stricmp(a,"QSV_TIME_HIGH"))			qsv=QSV_TIME_HIGH; \
	else if(!stricmp(a,"QSV_TIME_LOW"))			qsv=QSV_TIME_LOW; \
	else if(!stricmp(a,"QSV_TOTAVAILMEM"))			qsv=QSV_TOTAVAILMEM; \
	else if(!stricmp(a,"QSV_TOTPHYSMEM"))			qsv=QSV_TOTPHYSMEM; \
	else if(!stricmp(a,"QSV_TOTRESMEM"))			qsv=QSV_TOTRESMEM; \
	else if(!stricmp(a,"QSV_VERSION_MAJOR"))		qsv=QSV_VERSION_MAJOR; \
	else if(!stricmp(a,"QSV_VERSION_MINOR"))		qsv=QSV_VERSION_MINOR; \
	else if(!stricmp(a,"QSV_VERSION_REVISION"))	qsv=QSV_VERSION_REVISION; \
	else if(!stricmp(a,"QSV_VIRTUALADDRESSLIMIT"))	qsv=QSV_VIRTUALADDRESSLIMIT; \
	else return INVALID_ROUTINE;
